config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tracks do
    resources :chapters, only: %i[] do
      resources :subjects, only: %i[] do
        resources :lessons, only: %i[index]
      end
    end
  end
  root to: 'tracks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
    belongs_to :track
    has_many :subjects
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user
  belongs_to :track
  
end

app/models/lesson.rb
class Lesson < ApplicationRecord
    belongs_to :subject
    enum lesson_type: { Artigo: 0, Glossário: 1, Apostila: 2, Livro: 3, Vídeo: 4, Live: 5, Curso: 6, Podcast: 7 }
end

app/models/subject.rb
class Subject < ApplicationRecord
    belongs_to :chapter
    has_many :lessons
end

app/models/track.rb
class Track < ApplicationRecord
    has_many :enrollments
    has_many :users, through: :enrollments
    has_many :chapters
    has_many :subjects, through: :chapters
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :enrollments
  has_many :tracks, through: :enrollments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
    def index
        @chapters = Chapter.all
      end

      def new
        @chapter = Chapter.new
      end

      def create
        @chapter = Chapter.new(chapter_params)
        if @chapter.save
          redirect_to chapter_path(@chapter)
        else
          render :new
        end
      end

      def show
        @chapter = Chapter.find(params[:id])
      end

      def edit
        @chapter = Chapter.find(params[:id])
      end

      def update
        @chapter = Chapter.find(params[:id])
        if @chapter.update(chapter_params)
          redirect_to chapter_path(@chapter)
        else
          render :new
        end
      end

      def destroy
        @chapter = Chapter.find(params[:id])
        @chapter.destroy

        redirect_to chapters_path
      end

      private

      def chapter_params
        params.require(:chapter).permit(:name, :thumb_url)
      end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :get_subject, :get_chapter

  def index
    @lessons = @subject.lessons
    @track = @lessons[0].subject.chapter.track
  end

  def new
    @lesson = @subject.lessons.build
  end

  def create
    @lesson = @subject.lessons.build(lesson_params)
    if @lesson.save
      redirect_to subject_lessons_path(@subject)
    else
      render :new
    end
  end

  def show
    @lesson = Lesson.find(params[:id])
  end

  def edit
    @lesson = Lesson.find(params[:id])
  end

  def update
    @lesson = Lesson.find(params[:id])
    if @lesson.update(lesson_params)
      redirect_to subject_lessons_path(@subject)
    else
      render :new
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy

    redirect_to subject_lessons_path
  end

  def get_subject
    @subject = Subject.find(params[:subject_id])
    # @subjects = Subject.all
  end

  def get_chapter
    @chapter = Chapter.find(params[:chapter_id])
  end

  private

  def lesson_params
    params.require(:lesson).permit(:name, :lesson_type, :author, :duration, :source_url)
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :get_chapter

  def index
    @subjects = @chapter.subjects
  end

  def new
    @subject = @chapter.subjects.build
  end

  def create
    @subject = @chapter.subjects.build(subject_params)
    if @subject.save
      redirect_to chapter_subjects_path(@chapter)
    else
      render :new
    end
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update(subject_params)
      redirect_to chapter_subjects_path(@chapter)
    else
      render :new
    end
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy

    redirect_to chapter_subjects_path
  end

  def get_chapter
    @chapter = Chapter.find(params[:chapter_id])
    @chapters = Chapter.all
  end

  private

  def subject_params
    params.require(:subject).permit(:name)
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def index
    @tracks = Track.all
  end

  def new
    @track = Track.new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_path(@track)
    else
      render :new
    end
  end

  def show
    @track = Track.find(params[:id])
    @chapter_completed = false
    @lessons_types = []
  end

  def edit
    @track = Track.find(params[:id])
  end

  def update
    @track = Track.find(params[:id])
    if @track.update(track_params)
      redirect_to track_path(@track)
    else
      render :new
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy

    redirect_to root_path
  end

  private

  def track_params
    params.require(:track).permit(:name, :description, :thumb_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/chapters/edit.html.erb
<%= render 'shared/form_chapter' %>

app/views/chapters/index.html.erb
<h1>Capitulos</h1>

<p>Essa é a página que vai conter todos os capitulos</p>


<% @chapters.each do |chapter| %>
  <h3> <%= chapter.name %></h3>
    <ul>
      <% chapter.subjects.each do |subject| %>
  
  <%
=begin%>
 <li><%= chapter.name %> | <%=  link_to 'Editar', edit_chapter_path(chapter) %> | <%= link_to 'Remover', chapter_path(chapter), method: :delete, data: {confirm: 'Are you sure?'} %></li> 
<%
=end%>
        <li><%= subject.name %></li>
      <% end  %>
    </ul>
<% end  %>

app/views/chapters/new.html.erb
<%= render 'shared/form_chapter' %>

app/views/chapters/show.html.erb
<p><%= @chapter.name %></p>
<p><%= @chapter.thumb_url %></p>


<%= link_to 'Voltar para home', chapters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OrangeJuiceEvolutionSquad24</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;700&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lessons/edit.html.erb
<%= render 'shared/form_lesson' %>

app/views/lessons/index.html.erb
<%= render partial: "shared/header_track_name.html" %>

<div class="lessons-container">
  <section class="lessons-content">
    <%= link_to '← Voltar', :back, style:'back-button' %>
    <% @subject.lessons.each do |lesson| %>
    <h2><%= lesson.name %></h2>
    <p class='lesson-description'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti ullam eveniet veritatis expedita consequatur recusandae ex illum impedit aliquam, cupiditate est similique quaerat, porro vel. Maiores commodi ullam consectetur voluptatibus!</p>
    <hr>
    <div class="lesson-info-detail">
      <p><b>Tipo de Mídia</b></p>
      <p><%= lesson.lesson_type %></p>
    </div>
    <hr>
    <div class="lesson-info-detail">
      <p><b>Autor</b></p>
      <p><%= lesson.author %></p>
    </div>
    <hr>
    <%= link_to 'Iniciar aula', "http://#{lesson.source_url}", :class => "button-start-lesson" %>
    <% end %>
  </section>
  <div class='lesson-cards-section'>
    <p class='lesson-breadcrumb'><%= @chapter.name %> > <%= @subject.name %></p>
    <div class="lessons-list">

      <% @subject.lessons.each do |lesson| %>
      <div class="lesson-card">
        <% if lesson.completed %>
          <i class="fa-solid fa-circle-check check-icon-done"></i>
                <% else %>
          <i class="fa-solid fa-circle-check check-icon"></i>
        <% end %>
        <div class="lesson-info">
          <p class="lesson-card-title"><%= lesson.name %></p>
          <p class="lesson-length"><%= "#{lesson.duration} minutos" %></p>
        </div>
        <div class="lesson-type-icon">
          <% case lesson.lesson_type_before_type_cast %>
            <% when (0..4) %>
              <i class="fa-regular fa-file-lines"></i>
            <% when (4..6) %>
              <i class="fa-regular fa-circle-play"></i>
            <% when 7 %>
              <i class="fa-sharp fa-solid fa-headphones"></i>
          <% end %>
        </div>
      </div>
      <% end %>

    </div>
  </div>
</div>

app/views/lessons/new.html.erb
<%= render 'shared/form_lesson' %>

app/views/lessons/show.html.erb
<p><%= @lesson.name %></p>
<p><%= @lesson.source_url %></p>
<p><%= @lesson.duration %></p>
<p><%= @lesson.author %></p>
<p><%= @lesson.lesson_type %></p>


<%= link_to 'Voltar para home', :back %>

app/views/shared/_form_chapter.html.erb
<%= simple_form_for @chapter do |f| %>
  <%= f.input :name %>
  <%= f.input :thumb_url%>
  
  <%= f.button :submit %>
<% end %>

app/views/shared/_form_lesson.html.erb
<%= simple_form_for @lesson do |f| %>
  <%= f.input :name %>
  <%= f.input :lesson_type %>
  <%= f.input :author %>
  <%= f.input :source_url %>
  <%= f.input :duration, as: :numeric %>
 
  <%= f.button :submit %>
<% end %>

app/views/shared/_form_subject.html.erb
<%= simple_form_for @subject do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/shared/_form_track.html.erb
<%= simple_form_for @track do |f| %>
  <%= f.input :name %>
  <%= f.input :thumb_url %>
  <%= f.text_area :description %>
  <%= f.button :submit %>
<% end %>

app/views/shared/_header_track_name.html.erb
<header class = "header-track-name">
<figure>
  <img src=<%= @track.thumb_url %> alt="">
  <figcaption> Trilha <%= @track.name %>  </figcaption>
</figure>
</header>

app/views/shared/_navbar.html.erb
<nav>
  <div class="nav-container">
    <%= link_to root_path, class: "nav-logo" do %>
      <%= image_tag "https://d335luupugsy2.cloudfront.net/cms/files/107693/1654526197/$g74vm2w5o56" %>
    <% end %>
    <div class="nav-links">
      <% if user_signed_in? %>
        <span>Olá, <b><%= current_user.email %></b><br>
        <small><%= link_to 'Sair', destroy_user_session_path, method: :delete, :class => 'text-button' %></small></span>
        <div class="dropdown">
          <%= image_tag "https://github.com/erickhwk.png", class:'nav-avatar' %>
          <div class="dropdown-content">
            <%= link_to 'Editar Perfil', edit_user_registration_path, :class => 'a' %>
          </div>
        </div>










      <% else %>
        <%= link_to 'Entrar', new_user_session_path, class: "nav-link" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/subjects/edit.html.erb
<%= render 'shared/form_subject' %>

app/views/subjects/index.html.erb
<h1>Subjects</h1>

<% @chapters.each do |chapter| %>
  <h4><%= chapter.name %></h4>
  <ul>
  <% chapter.subjects.each do |subject| %>
    <li><%= subject.name %></li>
  <% end %>
  </ul>
<% end %>
</ul>

app/views/subjects/new.html.erb
<%= render 'shared/form_subject' %>

app/views/subjects/show.html.erb
<p><%= @subject.name %></p>

<%= link_to 'Voltar para Assuntos', subjects_path %>

app/views/tracks/edit.html.erb
<%= render 'shared/form_track' %>

app/views/tracks/index.html.erb
<div class="track-container">

  <h1>Minhas Trilhas</h1>
  <div class="tracks-list">
    <% @tracks.each do |track| %>
      <div class="track-card">
        <div class='thumb-url-holder'>
          <%= image_tag "#{track.thumb_url}", :class => 'thumb-url' %>
        </div>
        <div class="track-card-info">
          <h3><%= link_to track.name, track_path(track) %></h2>
          <div id="progress-body-coontainer">
            <div id="progress-container">
              <div id="circular-progress">
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

    
    <div class="discord-box"><a href="https://discord.gg/orangejuicetech">
      <span>Junte-se agora às nossas salas de estudo!</span>
    </a>
    <i class="fa-brands fa-discord fa-2x"></i>
  </div>
  <div class="links-section">
  <div class="video-thumbs">
      <h2>Conteúdos imperdíveis em vídeo</h2>
      <div class='flex'>
        <iframe width="350" height="200" src="https://www.youtube.com/embed/h89a4GoN3vw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="350" height="200" src="https://www.youtube.com/embed/yBSVgcO3HB8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </div>
    <div class="community-content">
      <h2>Mais conteúdos da comunidade</h2>
      <ul>
        <li><i class="fa-brands fa-youtube fa-2x"></i> Canal Orange</li>
        <li><i class="fa-brands fa-spotify fa-2x"></i> Orange Juice Cast</li>
        <li><i class="fa-brands fa-twitch fa-2x"></i> Orange Talks</li>
      </ul>
    </div>
  </div>
</div>

app/views/tracks/new.html.erb
<%= render 'shared/form_track' %>

app/views/tracks/show.html.erb
<%= render partial: "shared/header_track_name.html" %>


<main class = "track-show-main">

  <section class = "track-show-content">

    <section class = "track-show-heading">
    <%= link_to '← Voltar', root_path , style:'back-button' %>
    <h2> CONTEÚDO </h2> 
    </section>

    <section class = "track-show-chapters-subjects">
      <% @track.chapters.each do |chapter| %>
        <div class = "track-show-chapters">
          <header class = "track-show-chapters-header"> <h2> <%= chapter.name %></h2> </header>
          <div class = "track-show-subjects">
            <ul>
              <% chapter.subjects.each do |subject|  %>
              <% @lessons_types.clear %>
              <li>
                <div class = "track-show-subjects-check">
                  <% subject.lessons.each do | lesson | %>
                  <% @chapter_completed = lesson.completed %>
                  <% end %>
                  <% if @chapter_completed %>
                    <i class="fa-solid fa-circle-check check-icon-done"></i>
                  <% else %>
                    <i class="fa-solid fa-circle-check check-icon"></i>
                  <% end %>

                </div>  
                <%= link_to subject.name, track_chapter_subject_lessons_path(@track,chapter,subject), class: "track-show-lesson-link" %>
                <div class = "track-show-subjects-type">
                  <% subject.lessons.each do | lesson | %>
                  <% @lessons_types.append(lesson.lesson_type_before_type_cast) %>
                  <% end %>
                  <% if (@lessons_types.any?(4..6) ) %>
                    <i class="fa-regular fa-circle-play"></i>
                  <% end %>
                  <% if (@lessons_types.any?(0..3)) %>
                    <i class="fa-regular fa-file-lines"></i>
                  <% end %>
                  <% if (@lessons_types.any?(7) ) %>
                    <i class="fa-sharp fa-solid fa-headphones"></i>
                  <% end %>
                </div>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end  %>
    </section>
  </section>
</main>